feat: per-server quotapoints
ToogaInc/ToogaBooga pull request #262
Opened 2022-12-15 05:24 UTC by nyapat

for now, with the ts-ignore calls, ~~it works *with* the old data (i think, i had to delete it to make it work)~~ (does not)

2022-12-15 23:14 UTC, dmansdman commented
Fix ESLINT code scan

2022-12-18 02:51 UTC, ewang2002 commented on src/commands/logging/AddQuotaPoints.ts
> -        const points = ctx.interaction.options.getInteger("points", false) ?? 20;
copy and paste go brrr

2022-12-18 03:20 UTC, ewang2002 requested changes
Didn't test it fully, but please see my one comment.

2022-12-18 03:20 UTC, ewang2002 commented on src/commands/general/Stats.ts
> +            description += `\nQuota Points: ${stats.quotaPoints}`;
This is a certified `[object Object]` moment 

![image](https://user-images.githubusercontent.com/37031713/208279727-93db9a29-7593-4d4b-b4ca-1dca82969795.png)

2022-12-18 03:26 UTC, ewang2002 commented
lmao perfect. Thanks, I'll continue looking.

@nyapat one more thing -- can you bump the version to 1.3.1? Might as well do that in this PR since it's open

2022-12-18 04:04 UTC, ewang2002 approved these changes
Looks good to me

2022-12-18 04:04 UTC, merged