Added 'Realm Clearing' and 'Exalt Dungeon' HCs., 'Speedy' react, and updated 'logrun', 'headcount' and 'afkcheck' dungeon shortcuts.
ToogaInc/ToogaBooga pull request #285
Opened 2023-05-25 00:39 UTC by sjkd23

- Added Realm Clearing and Exalt Dungeon as options for headcount/afkcheck

- Added the Speedy reaction emoji (for realm clearing HC)

- Updated the "dungeon" option shortcut for the logrun, headcount and afkcheck commands. Now includes ALL exalt dungeons and 'Misc' for miscellaneous dungeons.

2023-06-04 08:52 UTC, ewang2002 requested changes
As pat mentioned, make the O3 string choice a constant.

2023-06-04 08:52 UTC, ewang2002 commented on src/commands/logging/LogRun.ts
>                              { name: "o3", value: "ORYX_3" },
No idea why I never got notified about this, but yes -- make this a constant.

2023-06-04 20:23 UTC, sjkd23 commented
> As pat mentioned, make the O3 string choice a constant.

I dont currently know how to do this. But will attempt to figure it out. Probably.

2023-06-04 22:52 UTC, sjkd23 commented
Ok I think I did it right. It works with the test bot, and dmans is the one that walked me through it, so it should be good!

2023-06-05 01:41 UTC, sjkd23 commented
Added DUNGEON_SHORTCUTS as a type in types.ts 

Added Dungeon_Shortcuts as a constant in GeneralConstants

Exported dungeon shortcuts in logrun, headcount, and afkcheck commands,

2023-06-05 06:54 UTC, ewang2002 approved these changes
Nice refactoring.

2023-06-05 06:54 UTC, merged